### ISSUE TITLE
Error object isn't logging

### ISSUE THREAD

**Issue by vitorabner** [pagarme/escriba#19]
When we try to log error object the escriba shows an empty object

**Comment by mccraveiro** [comment]
We need to stringify both `error.message` and `error.stack`
Working example: https://codepen.io/anon/pen/eRoEMe?editors=0011

**Comment by vitorabner** [comment]
Yep thanks, I'll push this fix tomorrow.

**Comment by felquis** [comment]
@vitorabner remember of using assignees when applicable and also [especial commit messages](https://help.github.com/articles/closing-issues-using-keywords/)
