### ISSUE TITLE
Allow user to get logId from a parameter of their choice

### ISSUE THREAD

**Issue by vitorabner** [pagarme/escriba#22]
Escriba should get an in from a field that will be chosen by user.

example: 

```json
"logId": {
    "name": "id",
    "from": ["body", "header"]
}
```

**Comment by mccraveiro** [comment]
@vitorabner could you add a description? It's not clear for me what this issue is about.

**Comment by vitorabner** [comment]
https://github.com/pagarme/escriba/pull/35
